name: unban
version: '1.0'
main: org.example.bk.untitled.Unban
api-version: '1.20'
authors: [Amauri Buenodos Santos]
description: Desbanir Players
commands:
  unban:
    description: Desbane um jogador pelo nome.
    usage: /unban <nome_do_jogador>
